name = "DataAnalyticsPlatform"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]

[deps]
Genie = "c43c736e-a2d1-11e8-25f2-5c8c7c7c7c7c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
